from django.db import models

class Tala(models.Model):
    faravardin = models.PositiveIntegerField()
    ordibehesht = models.PositiveIntegerField()
    khordad = models.PositiveIntegerField()
    tir = models.PositiveIntegerField()
    mordad = models.PositiveIntegerField()
    shahrivar = models.PositiveIntegerField()
    mehr = models.PositiveIntegerField()
    aban = models.PositiveIntegerField()
    azar = models.PositiveIntegerField()
    day = models.PositiveIntegerField()
    bahman= models.PositiveIntegerField()
    esfand = models.PositiveIntegerField()

class Noghreh(models.Model):
    faravardin = models.PositiveIntegerField()
    ordibehesht = models.PositiveIntegerField()
    khordad = models.PositiveIntegerField()
    tir = models.PositiveIntegerField()
    mordad = models.PositiveIntegerField()
    shahrivar = models.PositiveIntegerField()
    mehr = models.PositiveIntegerField()
    aban = models.PositiveIntegerField()
    azar = models.PositiveIntegerField()
    day = models.PositiveIntegerField()
    bahman= models.PositiveIntegerField()
    esfand = models.PositiveIntegerField()
    
class Mes(models.Model):
    faravardin = models.PositiveIntegerField()
    ordibehesht = models.PositiveIntegerField()
    khordad = models.PositiveIntegerField()
    tir = models.PositiveIntegerField()
    mordad = models.PositiveIntegerField()
    shahrivar = models.PositiveIntegerField()
    mehr = models.PositiveIntegerField()
    aban = models.PositiveIntegerField()
    azar = models.PositiveIntegerField()
    day = models.PositiveIntegerField()
    bahman= models.PositiveIntegerField()
    esfand = models.PositiveIntegerField()
    
class Naft(models.Model):
    faravardin = models.PositiveIntegerField()
    ordibehesht = models.PositiveIntegerField()
    khordad = models.PositiveIntegerField()
    tir = models.PositiveIntegerField()
    mordad = models.PositiveIntegerField()
    shahrivar = models.PositiveIntegerField()
    mehr = models.PositiveIntegerField()
    aban = models.PositiveIntegerField()
    azar = models.PositiveIntegerField()
    day = models.PositiveIntegerField()
    bahman= models.PositiveIntegerField()
    esfand = models.PositiveIntegerField()
    
    
class Foolad(models.Model):
    faravardin = models.PositiveIntegerField()
    ordibehesht = models.PositiveIntegerField()
    khordad = models.PositiveIntegerField()
    tir = models.PositiveIntegerField()
    mordad = models.PositiveIntegerField()
    shahrivar = models.PositiveIntegerField()
    mehr = models.PositiveIntegerField()
    aban = models.PositiveIntegerField()
    azar = models.PositiveIntegerField()
    day = models.PositiveIntegerField()
    bahman= models.PositiveIntegerField()
    esfand = models.PositiveIntegerField()